### PR TITLE
Better serialization for DSL objects.

### PR DESCRIPTION
**Pull request by hollinwilkins**
This change makes it so that DSL objects are directly serialized to JSON instead of converting to protobuf objects first.

### CODE REVIEW

**Comment by prianna** [comment]
@hollinwilkins I don't have permission to merge this.

**Comment by hollinwilkins** [comment]
@prianna Created a group "MLeap Contributors" and invited you to it

**Comment by prianna** [comment]
[!][unlock](http://i.giphy.com/TLVcxx5uvmuhG.gif)

**Comment by prianna** [comment]
unlock

**Pull request merged**
